# Generated by Django 2.1.2 on 2018-10-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cognome', models.CharField(max_length=50)),
                ('caratt', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Indagato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Magistrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prot', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipologia', models.PositiveSmallIntegerField(choices=[(100, ''), (0, 'Penale'), (1, 'Civile')])),
                ('rgnr', models.CharField(max_length=10)),
                ('fncr', models.CharField(choices=[('FNCR', 'FNCR'), ('Ignoti', 'Ignoti')], max_length=10)),
                ('data_delega', models.DateField()),
                ('attivita', models.TextField(blank=True, max_length=1000, null=True)),
                ('data_restituzione', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Agente')),
                ('indagati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Indagato')),
                ('magistrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Magistrato')),
            ],
        ),
    ]
